name = "doop-shopify"
client_id = "7d7626b911a18381852e202d80397317"
application_url = "https://doopshop.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "doop-shop.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_inventory,write_inventory,read_orders,write_orders"

[auth]
redirect_urls = ["https://doopshop.vercel.app/auth/callback"]

[webhooks]
api_version = "2024-01" 