name = "doop-shopify"
client_id = ""
application_url = ""
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_inventory,write_inventory,read_orders,write_orders"

[auth]
redirect_urls = ["https://localhost:3000/auth/callback"]

[webhooks]
api_version = "2024-01" 